# name: Login-Test
# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-24.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           command: npm run test:TestLogin

#       - name: Test Report
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: Electron Test Report
#           path: cypress/reports/html
