name: Cypress Test Runner

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Run tests in serial or parallel mode"
        required: true
        type: choice
        default: "serial"
        options:
          - serial
          - parallel

      browsers:
        description: "Comma-separated list of browsers (chrome,firefox,edge)"
        required: false
        default: "chrome"

      spec_pattern:
        description: "Test spec pattern (glob)"
        required: false
        default: "cypress/e2e/**/*.cy.js"
jobs:
  run-serial:
    if: ${{inputs.run_mode=='serial'}}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cypress
        run: |
          npm ci
          npx cypress install

      - name: Install Reporting Tools
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator

      - name: Run Cypress Tests Serially
        if: always()
        run: |
          IFS=',' read -ra BROWSER_LIST <<< "${{ inputs.browsers }}"
          for browser in "${BROWSER_LIST[@]}"; do
           echo "Running Cypress tests on $browser"
           REPORT_DIR="cypress/reports/html/$browser"
           mkdir -p "$REPORT_DIR"
           npx cypress run \
             --browser "$browser" \
             --spec "${{ inputs.spec_pattern }}" \
             --reporter mochawesome \
             --reporter-options reportDir=$REPORT_DIR,overwrite=false,html=false,json=true \
             || echo "Tests failed for $browser, continuing with next browser"
          done

      - name: Merge Reports and Generate HTML
        run: |
          npx mochawesome-merge cypress/reports/html/*/*.json > cypress/reports/html/merged-report.json
          npx marge cypress/reports/html/merged-report.json --reportDir cypress/reports/html --reportFilename merged-report.html

      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: Final Merged Report
          path: cypress/reports/html
