name: Cypress Test Runner

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Run tests in serial or parallel mode"
        required: true
        type: choice
        default: "serial"
        options:
          - serial
          - parallel

      browsers:
        description: "Comma-separated list of browsers (chrome,firefox,edge)"
        required: false
        default: "chrome"

      spec_pattern:
        description: "Test spec pattern (glob)"
        required: false
        default: "cypress/e2e/**/*.cy.js"

jobs:
  run-serial:
    if: ${{inputs.run_mode=='serial'}}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cypress
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress Tests Serially
        run: |
          IFS=',' read -ra BROWSER_LIST <<< "${{ inputs.browsers }}"
          for browser in "${BROWSER_LIST[@]}"; do
            REPORT_DIR="cypress/reports/html/$browser"
            mkdir -p "$REPORT_DIR"
            npx cypress run --browser "$browser" --spec "${{ inputs.spec_pattern }}" --reporter mochawesome --reporter-options reportDir=$REPORT_DIR,reportFilename=report-$browser.json
            ls -R cypress/reports/html/$browser  # Debugging line
          done

      - name: Merge Reports
        run: |
          mochawesome-merge cypress/reports/html/*/*.json > cypress/reports/html/merged-report.json

      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: Merged Report
          path: cypress/reports/html/merged-report.json
