name: Cypress Test Runner

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Run tests in serial or parallel mode"
        required: true
        type: choice
        default: "serial"
        options:
          - serial
          - parallel

      browsers:
        description: "Comma-separated list of browsers (chrome, firefox, edge)"
        required: false
        default: "chrome"

      spec_pattern:
        description: "Test spec pattern (glob)"
        required: false
        default: "cypress/e2e/**/*.cy.js"
jobs:
  run-serial:
    if: ${{inputs.run_mode=='serial'}}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Install Firefox
        run: |
          sudo apt update
          sudo apt install -y firefox

      - name: Run Tests
        run: |
          IFS=',' read -ra BROWSER_LIST <<< "${{ inputs.browsers }}"
          for browser in "${BROWSER_LIST[@]}"; do
            echo "Running Cypress tests on $browser"
            npx cypress run --browser "$browser" --spec "${{ inputs.spec_pattern }}"
          done

      - name: Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Browser Test Report
          path: cypress/reports/html
